/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        error: '#ffb4ab',
        'inverse-primary': '#006c4b',
        'on-surface-variant': '#bbcac0',
        'surface-container-high': '#232a3a',
        'on-secondary-container': '#00374d',
        secondary: '#7bd0ff',
        'on-primary-container': '#00563b',
        'on-tertiary-container': '#343ea7',
        'error-container': '#93000a',
        primary: '#5af0b3',
        'tertiary-container': '#afb6ff',
        'surface-variant': '#2e3545',
        'tertiary-fixed': '#e0e0ff',
        'on-tertiary-fixed': '#000767',
        'surface-container-lowest': '#070e1d',
        'inverse-on-surface': '#293040',
        'inverse-surface': '#dce2f7',
        'primary-fixed-dim': '#45dfa4',
        'on-background': '#dce2f7',
        'on-tertiary': '#131e8c',
        surface: '#0c1322',
        'on-error-container': '#ffdad6',
        'on-secondary': '#00354a',
        'on-surface': '#dce2f7',
        'on-secondary-fixed': '#001e2c',
        background: '#0c1322',
        'secondary-fixed': '#c4e7ff',
        outline: '#85948b',
        'on-error': '#690005',
        'surface-container-low': '#141b2b',
        'surface-tint': '#45dfa4',
        'surface-container': '#191f2f',
        'on-tertiary-fixed-variant': '#2f3aa3',
        'secondary-container': '#00a6e0',
        'on-primary-fixed': '#002114',
        'surface-bright': '#323949',
        'secondary-fixed-dim': '#7bd0ff',
        'surface-container-highest': '#2e3545',
        'on-primary': '#003825',
        'primary-fixed': '#68fcbf',
        'surface-dim': '#0c1322',
        'on-secondary-fixed-variant': '#004c69',
        'tertiary-fixed-dim': '#bdc2ff',
        'on-primary-fixed-variant': '#005137',
        tertiary: '#d2d4ff',
        'primary-container': '#34d399',
        'outline-variant': '#3c4a42',
      },
      fontFamily: {
        headline: ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        body: ['var(--font-inter)', 'Inter', 'sans-serif'],
        label: ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
